In [1]:
import numpy as np
import pandas as pd

# Project: Credit Risk Multi-Class Classification

## 1. Problem Statement
The objective of this project is to build a predictive model that classifies loan applicants into one of four risk categories—**P1, P2, P3, and P4**—based on historical credit bureau data and demographic information. 

These categories serve as priority levels that determine a customer's loan eligibility and interest rate pricing:
* **P1 & P2:** High-quality applicants with low to moderate risk.
* **P3:** Higher-risk applicants who may require stricter terms.
* **P4:** Very high-risk applicants who are likely to be ineligible for credit.

## 2. Technical Scope
The model utilizes a comprehensive dataset containing over 60 variables, categorized as follows:
* **Tradeline Information:** Total accounts, types of loans (Secured/Unsecured), and account ages.
* **Delinquency Metrics:** Historical "Days Past Due" (DPD) performance and frequency of missed payments.
* **Enquiry Behavior:** Frequency of credit searches in the last 3, 6, and 12 months.
* **Demographics:** Income, age, education, and employment stability.

## 3. Business Goal
By automating this classification, the institution aims to:
1.  **Reduce Credit Loss:** Identify and filter out high-risk (P4) individuals.
2.  **Optimize Approval Rates:** Streamline the process for low-risk (P1/P2) applicants.
3.  **Risk-Based Pricing:** Tailor interest rates based on the specific risk tier (P1–P4).

## 4. Evaluation Metrics
Success will be measured by the model's ability to accurately differentiate between the classes, prioritizing high **Recall for P4** (to avoid lending to risky customers) and high **Precision for P1** (to ensure premium customers are correctly identified).



## Datasets
1. BOB BANK Customer Dataset Loan Centric
2. CIBIL Dataset

In [2]:
# Importing the data
a1 = pd.read_csv("Data/case_study1.xlsx - case_study1.csv")
a2 = pd.read_csv("Data/case_study2.xlsx - case_study2.csv")

In [3]:
df1 = a1.copy()
df2 = a2.copy()

In [4]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

## Feature Description for Dataset 1 - BOB Customer Dataset
| Variable Name | Description |
| :--- | :--- |
| **Total_TL** | Total trade lines/accounts in Bureau |
| **Tot_Closed_TL** | Total closed trade lines/accounts |
| **Tot_Active_TL** | Total active accounts |
| **Total_TL_opened_L6M** | Total accounts opened in last 6 Months |
| **Tot_TL_closed_L6M** | Total accounts closed in last 6 months |
| **pct_tl_open_L6M** | Percent accounts opened in last 6 months |
| **pct_tl_closed_L6M** | Percent accounts closed in last 6 months |
| **pct_active_tl** | Percent active accounts |
| **pct_closed_tl** | Percent closed accounts |
| **Total_TL_opened_L12M** | Total accounts opened in last 12 Months |
| **Tot_TL_closed_L12M** | Total accounts closed in last 12 months |
| **pct_tl_open_L12M** | Percent accounts opened in last 12 months |
| **pct_tl_closed_L12M** | Percent accounts closed in last 12 months |
| **Tot_Missed_Pmnt** | Total missed Payments |
| **Auto_TL** | Count Automobile accounts |
| **CC_TL** | Count of Credit card accounts |
| **Consumer_TL** | Count of Consumer goods accounts |
| **Gold_TL** | Count of Gold loan accounts |
| **Home_TL** | Count of Housing loan accounts |
| **PL_TL** | Count of Personal loan accounts |
| **Secured_TL** | Count of secured accounts |
| **Unsecured_TL** | Count of unsecured accounts |
| **Other_TL** | Count of other accounts |
| **Age_Oldest_TL** | Age of oldest opened account |
| **Age_Newest_TL** | Age of newest opened account |

In [5]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

## Feature Description for Dataset 2 - CIBIL Score

| Variable Name | Description |
| :--- | :--- |
| **time_since_recent_payment** | Time Since recent Payment made |
| **time_since_first_deliquency** | Time since first Deliquency (missed payment) |
| **time_since_recent_deliquency** | Time Since recent Delinquency |
| **num_times_delinquent** | Number of times delinquent |
| **max_delinquency_level** | Maximum delinquency level |
| **max_recent_level_of_deliq** | Maximum recent level of delinquency |
| **num_deliq_6mts** | Number of times delinquent in last 6 months |
| **num_deliq_12mts** | Number of times delinquent in last 12 months |
| **num_deliq_6_12mts** | Number of times delinquent between last 6 months and last 12 months |
| **max_deliq_6mts** | Maximum delinquency level in last 6 months |
| **max_deliq_12mts** | Maximum delinquency level in last 12 months |
| **num_times_30p_dpd** | Number of times 30+ dpd |
| **num_times_60p_dpd** | Number of times 60+ dpd |
| **num_std** | Number of standard Payments |
| **num_std_6mts** | Number of standard Payments in last 6 months |
| **num_std_12mts** | Number of standard Payments in last 12 months |
| **num_sub** | Number of sub standard payments - not making full payments |
| **num_sub_6mts** | Number of sub standard payments in last 6 months |
| **num_sub_12mts** | Number of sub standard payments in last 12 months |
| **num_dbt** | Number of doubtful payments |
| **num_dbt_6mts** | Number of doubtful payments in last 6 months |
| **num_dbt_12mts** | Number of doubtful payments in last 12 months |
| **num_lss** | Number of loss accounts |
| **num_lss_6mts** | Number of loss accounts in last 6 months |
| **num_lss_12mts** | Number of loss accounts in last 12 months |
| **recent_level_of_deliq** | Recent level of delinquency |
| **tot_enq** | Total enquiries |
| **CC_enq** | Credit card enquiries |
| **CC_enq_L6m** | Credit card enquiries in last 6 months |
| **CC_enq_L12m** | Credit card enquiries in last 12 months |
| **PL_enq** | Personal Loan enquiries |
| **PL_enq_L6m** | Personal Loan enquiries in last 6 months |
| **PL_enq_L12m** | Personal Loan enquiries in last 12 months |
| **time_since_recent_enq** | Time since recent enquiry |
| **enq_L12m** | Enquiries in last 12 months |
| **enq_L6m** | Enquiries in last 6 months |
| **enq_L3m** | Enquiries in last 3 months |
| **MARITALSTATUS** | Marital Status |
| **EDUCATION** | Education level |
| **AGE** | Age |
| **GENDER** | Gender |
| **NETMONTHLYINCOME** | Net Monthly Income |
| **Time_With_Curr_Empr** | Time with current Employer |
| **pct_of_active_TLs_ever** | Percent active accounts ever |
| **pct_opened_TLs_L6m_of_L12m** | Percent accounts opened in last 6 months to last 12 months |
| **pct_currentBal_all_TL** | Percent current balance of all accounts |
| **CC_utilization** | Credit card utilization |
| **CC_Flag** | Credit card Flag |
| **PL_utilization** | Personal Loan utilization |
| **PL_Flag** | Personal Loan Flag |
| **pct_PL_enq_L6m_of_L12m** | Percent enquiries PL in last 6 months to last 12 months |
| **pct_CC_enq_L6m_of_L12m** | Percent enquiries CC in last 6 months to last 12 months |
| **pct_PL_enq_L6m_of_ever** | Percent enquiries PL in last 6 months to last 6 months |
| **pct_CC_enq_L6m_of_ever** | Percent enquiries CC in last 6 months to last 6 months |
| **max_unsec_exposure_inPct** | Maximum unsecured exposure in percent |
| **HL_Flag** | Housing Loan Flag |
| **GL_Flag** | Gold Loan Flag |
| **last_prod_enq2** | Latest product enquired for |
| **first_prod_enq2** | First product enquired for |
| **Credit_Score** | Applicant's credit score |
| **Approved_Flag** | Priority levels |

## Data Cleaning - Dataset 1

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

In [8]:
df1.isnull().sum()

PROSPECTID              0
Total_TL                0
Tot_Closed_TL           0
Tot_Active_TL           0
Total_TL_opened_L6M     0
Tot_TL_closed_L6M       0
pct_tl_open_L6M         0
pct_tl_closed_L6M       0
pct_active_tl           0
pct_closed_tl           0
Total_TL_opened_L12M    0
Tot_TL_closed_L12M      0
pct_tl_open_L12M        0
pct_tl_closed_L12M      0
Tot_Missed_Pmnt         0
Auto_TL                 0
CC_TL                   0
Consumer_TL             0
Gold_TL                 0
Home_TL                 0
PL_TL                   0
Secured_TL              0
Unsecured_TL            0
Other_TL                0
Age_Oldest_TL           0
Age_Newest_TL           0
dtype: int64

In [10]:
df1.sample(5)

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
44385,44386,3,2,1,1,1,0.333,0.333,0.333,0.667,...,0,0,3,0,0,3,0,0,23,3
42062,42063,3,2,1,0,0,0.000,0.000,0.333,0.667,...,0,0,0,0,0,3,0,0,74,53
31828,31829,10,8,2,0,0,0.000,0.000,0.200,0.800,...,0,0,0,1,2,8,2,7,119,13
34949,34950,2,1,1,1,0,0.500,0.000,0.500,0.500,...,0,1,1,0,0,1,1,0,16,2
6866,6867,2,1,1,0,0,0.000,0.000,0.500,0.500,...,0,0,2,0,0,2,0,0,21,9

In [31]:
# By simple Observation we have column containing -99999
# Let's check every column for value -99999
for i in df1.columns:
    print(i,len(df1[df1[i]== -99999]))

PROSPECTID 0
Total_TL 0
Tot_Closed_TL 0
Tot_Active_TL 0
Total_TL_opened_L6M 0
Tot_TL_closed_L6M 0
pct_tl_open_L6M 0
pct_tl_closed_L6M 0
pct_active_tl 0
pct_closed_tl 0
Total_TL_opened_L12M 0
Tot_TL_closed_L12M 0
pct_tl_open_L12M 0
pct_tl_closed_L12M 0
Tot_Missed_Pmnt 0
Auto_TL 0
CC_TL 0
Consumer_TL 0
Gold_TL 0
Home_TL 0
PL_TL 0
Secured_TL 0
Unsecured_TL 0
Other_TL 0
Age_Oldest_TL 40
Age_Newest_TL 40

In [33]:
# As there are only 40 out of 51336 rows containing the -99999 value we can easily drop them
df1 = df1[df1['Age_Newest_TL']!= -99999]

In [34]:
for i in df1.columns:
    print(i,len(df1[df1[i]== -99999]))

PROSPECTID 0
Total_TL 0
Tot_Closed_TL 0
Tot_Active_TL 0
Total_TL_opened_L6M 0
Tot_TL_closed_L6M 0
pct_tl_open_L6M 0
pct_tl_closed_L6M 0
pct_active_tl 0
pct_closed_tl 0
Total_TL_opened_L12M 0
Tot_TL_closed_L12M 0
pct_tl_open_L12M 0
pct_tl_closed_L12M 0
Tot_Missed_Pmnt 0
Auto_TL 0
CC_TL 0
Consumer_TL 0
Gold_TL 0
Home_TL 0
PL_TL 0
Secured_TL 0
Unsecured_TL 0
Other_TL 0
Age_Oldest_TL 0
Age_Newest_TL 0

## Data Cleaning - Dataset 2

In [35]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  object
 39  EDUCATION                     51336 non-null  object
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  object
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  object
 59  first_prod_enq2               51336 non-null  object
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  object
dtypes: float64(10), int64(46), object(6)
memory usage: 24.3+ MB

In [36]:
df2.sample(5)

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
15900,15901,52,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,ConsumerLoan,others,661,P3
25295,25296,1437,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,1,0,others,others,691,P2
20077,20078,62,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.777,0,0,others,others,684,P2
17624,17625,101,-99999,-99999,0,-99999,0,0,0,0,...,0.0,1.0,0.0,0.529,0,0,PL,PL,672,P2
26091,26092,80,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,1,ConsumerLoan,ConsumerLoan,663,P3

In [37]:
# Again we have multiple columns with -99999 value
for i in df2.columns:
    print(i, len(df2[df2[i]== -99999]))

PROSPECTID 0
time_since_recent_payment 4291
time_since_first_deliquency 35949
time_since_recent_deliquency 35949
num_times_delinquent 0
max_delinquency_level 35949
max_recent_level_of_deliq 0
num_deliq_6mts 0
num_deliq_12mts 0
num_deliq_6_12mts 0
max_deliq_6mts 12890
max_deliq_12mts 10832
num_times_30p_dpd 0
num_times_60p_dpd 0
num_std 0
num_std_6mts 0
num_std_12mts 0
num_sub 0
num_sub_6mts 0
num_sub_12mts 0
num_dbt 0
num_dbt_6mts 0
num_dbt_12mts 0
num_lss 0
num_lss_6mts 0
num_lss_12mts 0
recent_level_of_deliq 0
tot_enq 6321
CC_enq 6321
CC_enq_L6m 6321
CC_enq_L12m 6321
PL_enq 6321
PL_enq_L6m 6321
PL_enq_L12m 6321
time_since_recent_enq 6321
enq_L12m 6321
enq_L6m 6321
enq_L3m 6321
MARITALSTATUS 0
EDUCATION 0
AGE 0
GENDER 0
NETMONTHLYINCOME 0
Time_With_Curr_Empr 0
pct_of_active_TLs_ever 0
pct_opened_TLs_L6m_of_L12m 0
pct_currentBal_all_TL 72
CC_utilization 47636
CC_Flag 0
PL_utilization 44435
PL_Flag 0
pct_PL_enq_L6m_of_L12m 0
pct_CC_enq_L6m_of_L12m 0
pct_PL_enq_L6m_of_ever 0
pct_CC_enq_L6m_of_ever 0
max_unsec_exposure_inPct 23178
HL_Flag 0
GL_Flag 0
last_prod_enq2 0
first_prod_enq2 0
Credit_Score 0
Approved_Flag 0

## Here we cannot impute the missing values as the column hold different significance,
## We will drop all the columns that have more than 10000 rows of null value
## Rest we will the rows itself

In [38]:
columns_to_be_removed = []
for i in df2.columns:
    if df2[df2[i]==-99999].shape[0] > 10000:
        columns_to_be_removed.append(i)
columns_to_be_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [39]:
df2.drop(columns_to_be_removed,axis=1,inplace = True)

In [41]:
df2.shape

(51336, 54)

In [42]:
for i in df2.columns:
    df2 = df2.loc[ df2[i] != -99999 ]

## Now both the datasets are cleaned, let's merge both the datasets

In [43]:
df = pd.merge(df1,df2,how ='inner',left_on = ['PROSPECTID'],right_on = ['PROSPECTID'])

In [44]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [46]:
# Save to CSV
df.to_csv('Data/data.csv', index=False)